version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: ./golang/Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./go-app:/go-app

  frontend:
    build:
      context: .
      dockerfile: ./react/Dockerfile
    volumes:
      - ./react-app:/react-app
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    container_name: "frontend"

  postgres:
      build:
        context: .
        dockerfile: ./postgres/Dockerfile
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=go_app
      ports:
        - "5432:5432"
      container_name: postgres

  postgres-gui:
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://postgres:secret@postgres/go_app?sslmode=disable
    links:
      - postgres:postgres
    ports:
      - "9232:8080"
    depends_on:
      - postgres