version: "3.3"
services:
  frontend:
    build:
      context: .
      dockerfile: "./react/Dockerfile"
    volumes:
      - ./go-app:/go-app
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    container_name: "frontend"