version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: ./golang/Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./go-app:/app
  frontend:
    build:
      context: .
      dockerfile: ./react/Dockerfile
    volumes:
      - ./react-app:/react-app
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    container_name: "frontend"