@startuml
start
  :リリース機能;
  repeat :要件定義;
    :基本設計;
    :開発・テスト方針確認会;
  repeat while(要件定義、基本設計に問題がないか？) is (いいえ) not (はい)
  repeat :詳細設計;
    :コーディング;
    :単体テスト;
    :内部結合;
    :外部結合;
    :開発内容デモ会;
  repeat while(開発内容に問題がないか？) is (いいえ) not (はい)
  :総合テスト;
  repeat :修正;
  :リリース判定;
  repeat while(リリース判定に問題がないか？) is (いいえ) not (はい)
  :リリース;
end
@enduml