@startuml
  entity Ticket{
    *ticketId
    --
  }
  entity User{
    *userId
    --
    name
  }
  entity UserTicketGroup{
    *UserTicketGroupId
    -- 
  }
  entity TicketGroup{
    *TicketGroupId
    -- 
  }
  entity TicketGrouping{
    *ticketGroupingId
    -- 
    ticketGroupId
    ticketId
  }
  entity Possess{
    *possessId
    -- 
    userId
    ticketId
  }
  entity UseUser{
    *useUserId
    --
    ticketId
    userId
  }
  entity TransferHistory{
    transferHistoryId
    --
    transferId
    transfed_at
    transfer_at
    UserTicketGroupId_from
    UserTicketGroupId_to
  }
  entity Transfer{
    transferId
    --
    ticketId
  }
  UserTicketGroup ||--o| User
  UserTicketGroup ||--o| Ticket
  User ||--o{Possess
  User ||--o| UseUser
  Ticket ||--o| Possess
  Ticket ||--o| TicketGrouping
  TicketGroup ||--|{ TicketGrouping
  Ticket ||--o| UseUser
  Transfer }o--||Ticket
  Transfer ||--||TransferHistory
@enduml